FROM quay.io/keycloak/keycloak:26.7.2 AS builder

ENV KC_DB=postgres \
    KC_HEALTH_ENABLED=true \
    KC_METRICS_ENABLED=true \
    KC_FEATURES=cimd \
    KC_HTTP_RELATIVE_PATH=/identity

RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:26.7.2

COPY --from=builder /opt/keycloak/ /opt/keycloak/

ENV KC_DB=postgres \
    KC_HEALTH_ENABLED=true \
    KC_METRICS_ENABLED=true \
    KC_FEATURES=cimd \
    KC_HTTP_RELATIVE_PATH=/identity

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
