import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import * as z from "zod/v4";
import { GovernanceRuntime } from "./core.js";

const jsonObject = z.record(z.string(), z.unknown());
const result = (value) => ({ content: [{ type: "text", text: JSON.stringify(value, null, 2) }], structuredContent: value });
const fail = (error) => ({ isError: true, content: [{ type: "text", text: error instanceof Error ? error.message : String(error) }] });
const guarded = (handler) => async (input) => { try { return result(await handler(input)); } catch (error) { return fail(error); } };

export function createPaloMcpServer(runtime = new GovernanceRuntime(), { exposedTools } = {}) {
  const server = new McpServer({ name: "palo-governance-server", version: "2.5.0", websiteUrl: "https://paloframework.org/PALO_AgenticGovernance.html" });
  const allowed = exposedTools ? new Set(exposedTools) : null;
  const registerTool = (name, definition, handler) => { if (!allowed || allowed.has(name)) server.registerTool(name, definition, handler); };
  registerTool("palo_register_agent", { description: "Developer preview: register or version a local PALO agent authority profile; publisher identity is not authenticated.", inputSchema: { caseId: z.string().min(1), profile: jsonObject } }, guarded(({ caseId, profile }) => runtime.registerAgent(caseId, profile)));
  registerTool("palo_register_policy", { description: "Developer preview: register a local OPA policy manifest; bundle attestation is not provided.", inputSchema: { policy: jsonObject } }, guarded(({ policy }) => runtime.registerPolicy(policy)));
  registerTool("palo_get_registry", { description: "List locally registered profile and policy versions without secret material.", inputSchema: {} }, guarded(() => runtime.getRegistry()));
  registerTool("palo_register_executor", { description: "Register a versioned trusted-executor manifest. Executable handlers must be provisioned by the runtime operator.", inputSchema: { manifest: jsonObject } }, guarded(({ manifest }) => runtime.registerExecutor(manifest)));
  registerTool("palo_register_verifier", { description: "Register a versioned authoritative-verifier manifest. Verifier handlers must be provisioned by the runtime operator.", inputSchema: { manifest: jsonObject } }, guarded(({ manifest }) => runtime.registerVerifier(manifest)));
  registerTool("palo_verify_action_authority", { description: "Developer preview: normalize and evaluate an Action Claim through local profile data and draft OPA policy; not a production authorization decision.", inputSchema: { claim: jsonObject, approvalId: z.string().optional() } }, guarded(({ claim, approvalId }) => runtime.verifyAction(claim, approvalId)));
  registerTool("palo_execute_governed_action", { description: "Execute an Action Claim 1.2 through a one-time capability, trusted executor and authoritative outcome verifier.", inputSchema: { claim: jsonObject, approvalId: z.string().optional(), executorId: z.string().min(1), verifierId: z.string().min(1), capabilityTtlSeconds: z.number().int().min(5).max(300).optional() } }, guarded(({ claim, approvalId, executorId, verifierId, capabilityTtlSeconds }) => runtime.executeGovernedAction(claim, { approvalId, executorId, verifierId, capabilityTtlSeconds })));
  registerTool("palo_get_execution_status", { description: "Read the receipt, outcome attestation and incident state for one governed execution.", inputSchema: { executionId: z.string().min(1) } }, guarded(({ executionId }) => runtime.getExecution(executionId)));
  registerTool("palo_verify_outcome", { description: "Re-run authoritative outcome verification for an execution, normally after an inconclusive result.", inputSchema: { executionId: z.string().min(1), force: z.boolean().optional() } }, guarded(({ executionId, force }) => runtime.verifyOutcome(executionId, { force: Boolean(force) })));
  registerTool("palo_request_approval", { description: "Create an expiring human approval bound to the exact Action Claim digest.", inputSchema: { claim: jsonObject, requestedBy: z.string().min(1), ttlSeconds: z.number().int().min(30).max(86400).optional() } }, guarded(({ claim, requestedBy, ttlSeconds }) => runtime.requestApproval(claim, undefined, requestedBy, ttlSeconds)));
  registerTool("palo_get_approval_status", { description: "Read one approval state, including automatic expiry.", inputSchema: { approvalId: z.string().min(1) } }, guarded(({ approvalId }) => runtime.getApproval(approvalId)));
  registerTool("palo_list_approvals", { description: "List approval work items for Web and mobile review surfaces.", inputSchema: { status: z.enum(["pending", "approved", "denied", "cancelled", "expired", "all"]).optional() } }, guarded(({ status }) => runtime.listApprovals(status || "pending")));
  registerTool("palo_resolve_approval", { description: "Prototype: resolve a pending approval once with a caller-supplied identity label and rationale; reviewer identity is not authenticated.", inputSchema: { approvalId: z.string().min(1), status: z.enum(["approved", "denied", "cancelled"]), resolvedBy: z.string().min(1), rationale: z.string().min(1).max(4000) } }, guarded(({ approvalId, status, resolvedBy, rationale }) => runtime.resolveApproval(approvalId, status, resolvedBy, rationale)));
  registerTool("palo_submit_evidence", { description: "Deprecated compatibility tool for explicitly trusted local callers. Governed execution generates receipt and outcome evidence internally.", inputSchema: { claim: jsonObject, decision: jsonObject, outcome: z.enum(["executed", "failed"]), payload: jsonObject.optional() } }, guarded(({ claim, decision, outcome, payload }) => runtime.recordEvidence({ claim, decision, outcome, payload })));
  registerTool("palo_verify_evidence", { description: "Verify an evidence envelope HMAC using protected server-side key material.", inputSchema: { envelope: jsonObject } }, guarded(({ envelope }) => ({ valid: runtime.verifyEvidence(envelope), eventId: envelope.eventId })));
  registerTool("palo_verify_ledger", { description: "Verify signatures and the complete append-only evidence hash chain.", inputSchema: {} }, guarded(() => runtime.verifyLedger()));
  registerTool("palo_list_incidents", { description: "List assurance incidents opened after mismatched or inconclusive outcomes.", inputSchema: { status: z.enum(["open", "acknowledged", "resolved", "all"]).optional() } }, guarded(({ status }) => runtime.listIncidents(status || "open")));
  registerTool("palo_get_incident", { description: "Read one assurance incident.", inputSchema: { incidentId: z.string().min(1) } }, guarded(({ incidentId }) => runtime.getIncident(incidentId)));
  registerTool("palo_resolve_incident", { description: "Acknowledge or resolve an assurance incident; compensation remains a separately governed Action Claim.", inputSchema: { incidentId: z.string().min(1), status: z.enum(["acknowledged", "resolved"]), resolvedBy: z.string().min(1), resolution: z.string().min(1).max(4000) } }, guarded(({ incidentId, status, resolvedBy, resolution }) => runtime.resolveIncident(incidentId, status, resolvedBy, resolution)));
  return server;
}
